// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// bindRelationDao is the data access object for the table bind_relation.
// You can define custom methods on it to extend its functionality as needed.
type bindRelationDao struct {
	*internal.BindRelationDao
}

var (
	// BindRelation is a globally accessible object for table bind_relation operations.
	BindRelation = bindRelationDao{internal.NewBindRelationDao()}
)

// Add your custom methods and functionality below.
