// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// communityServiceDao is the data access object for the table community_service.
// You can define custom methods on it to extend its functionality as needed.
type communityServiceDao struct {
	*internal.CommunityServiceDao
}

var (
	// CommunityService is a globally accessible object for table community_service operations.
	CommunityService = communityServiceDao{internal.NewCommunityServiceDao()}
)

// Add your custom methods and functionality below.
