// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// emergencyContactDao is the data access object for the table emergency_contact.
// You can define custom methods on it to extend its functionality as needed.
type emergencyContactDao struct {
	*internal.EmergencyContactDao
}

var (
	// EmergencyContact is a globally accessible object for table emergency_contact operations.
	EmergencyContact = emergencyContactDao{internal.NewEmergencyContactDao()}
)

// Add your custom methods and functionality below.
