// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// emergencyContactViewDao is the data access object for the table emergency_contact_view.
// You can define custom methods on it to extend its functionality as needed.
type emergencyContactViewDao struct {
	*internal.EmergencyContactViewDao
}

var (
	// EmergencyContactView is a globally accessible object for table emergency_contact_view operations.
	EmergencyContactView = emergencyContactViewDao{internal.NewEmergencyContactViewDao()}
)

// Add your custom methods and functionality below.
