// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// familyOverviewDao is the data access object for the table family_overview.
// You can define custom methods on it to extend its functionality as needed.
type familyOverviewDao struct {
	*internal.FamilyOverviewDao
}

var (
	// FamilyOverview is a globally accessible object for table family_overview operations.
	FamilyOverview = familyOverviewDao{internal.NewFamilyOverviewDao()}
)

// Add your custom methods and functionality below.
