// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// familyFeedDao is the data access object for the table family_feed.
// You can define custom methods on it to extend its functionality as needed.
type familyFeedDao struct {
	*internal.FamilyFeedDao
}

var (
	// FamilyFeed is a globally accessible object for table family_feed operations.
	FamilyFeed = familyFeedDao{internal.NewFamilyFeedDao()}
)

// Add your custom methods and functionality below.
