// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// healthDataDao is the data access object for the table health_data.
// You can define custom methods on it to extend its functionality as needed.
type healthDataDao struct {
	*internal.HealthDataDao
}

var (
	// HealthData is a globally accessible object for table health_data operations.
	HealthData = healthDataDao{internal.NewHealthDataDao()}
)

// Add your custom methods and functionality below.
