// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// reminderDao is the data access object for the table reminder.
// You can define custom methods on it to extend its functionality as needed.
type reminderDao struct {
	*internal.ReminderDao
}

var (
	// Reminder is a globally accessible object for table reminder operations.
	Reminder = reminderDao{internal.NewReminderDao()}
)

// Add your custom methods and functionality below.
