// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// serviceBookingDao is the data access object for the table service_booking.
// You can define custom methods on it to extend its functionality as needed.
type serviceBookingDao struct {
	*internal.ServiceBookingDao
}

var (
	// ServiceBooking is a globally accessible object for table service_booking operations.
	ServiceBooking = serviceBookingDao{internal.NewServiceBookingDao()}
)

// Add your custom methods and functionality below.
