// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"se_project/internal/dao/internal"
)

// sosAlertDao is the data access object for the table sos_alert.
// You can define custom methods on it to extend its functionality as needed.
type sosAlertDao struct {
	*internal.SosAlertDao
}

var (
	// SosAlert is a globally accessible object for table sos_alert operations.
	SosAlert = sosAlertDao{internal.NewSosAlertDao()}
)

// Add your custom methods and functionality below.
